### ISSUE TITLE
针对 从相册中 选取二维码 识别失败的问题 的解决办法

### ISSUE THREAD

**Issue by bigNiuSanMao** [kingsic/SGQRCode#106]
在选择图片成功的代理方法中 - (void)imagePickerController:(UIImagePickerController *)picker didFinishPickingMediaWithInfo:(NSDictionary<NSString *,id> *)info 

直接使用原生图片或者编辑后的图片 并且不做重绘处理（使用上下文生成的图片有问题）

解决方案：
替换方法 ：
 UIImage *image = [UIImage SG_imageSizeWithScreenImage:info[UIImagePickerControllerOriginalImage]];

为：

__block UIImage* image = [info objectForKey:UIImagePickerControllerEditedImage];    
    if (!image){
        image = [info objectForKey:UIImagePickerControllerOriginalImage];
    }

**Comment by kingsic** [comment]
非常感谢您能提供此问题的解决方案；让我再次审核这段代码，之前犯了一个低级却恶心错误 @bigNiuSanMao
