### ISSUE TITLE
拍照拍的二维码不可以识别，截图截的二维码可以识别。

### ISSUE THREAD

**Issue by LxwYl** [kingsic/SGQRCode#11]

**Comment by kingsic** [comment]
拍照的照片清晰度高了，是可以识别的，如果无法识别，你可以对你模糊的照片在进行图片处理 @LxwYl

**Comment by xiaosao6** [comment]
我试了一下  既然只有截图大小的图片被识别，因此可以将我们自己选的图片先进行缩小处理（如果超过屏幕尺寸），这样普通图片就可以跟截图一样被正常识别了

添加如下处理，返回给选择后的回调方法-scanQRCodeFromPhotosInTheAlbum

//返回不超过屏幕尺寸大小的UIImage
-(UIImage *)imgWithScreenSizedImage:(UIImage*)image{
    CGFloat origWidth  = image.size.width;
    CGFloat screenWidth = [UIScreen mainScreen].bounds.size.width;
    CGFloat origHeight = image.size.height;
    CGFloat screenHeight = [UIScreen mainScreen].bounds.size.height;
    
    if ( origWidth <= screenWidth && origHeight <= screenHeight) { return image; }
    
    NSLog(@"图片像素尺寸过大,压缩前w%f,h%f", origWidth, origHeight);
    CGFloat max = MAX(origWidth, origHeight);
    CGFloat scale = max/(screenHeight * 2.0f);//如果是6plus等设备，比例应该是3.0
    NSLog(@"压缩后w%f,h%f", origWidth/scale, origHeight/scale);
    return [self imgWithImage:image scaledToSize:CGSizeMake(origWidth/scale, origHeight/scale)];
}

-(UIImage *)imgWithImage:(UIImage*)image scaledToSize:(CGSize)newSize{
    UIGraphicsBeginImageContext(newSize);
    [image drawInRect:CGRectMake(0, 0, newSize.width, newSize.height)];
    UIImage* newImage = UIGraphicsGetImageFromCurrentImageContext();
    UIGraphicsEndImageContext();
    return newImage;
}

**Comment by kingsic** [comment]
非常感谢，过段时间就会处理这个问题




发自网易邮箱大师
在2017年03月27日 18:18，neo6 写道：

我试了一下 既然只有截图大小的图片被识别，因此可以将我们自己选的图片先进行缩小处理（如果超过屏幕尺寸），这样普通图片就可以跟截图一样被正常识别了

添加如下处理，返回给选择后的回调方法-scanQRCodeFromPhotosInTheAlbum

//返回不超过屏幕尺寸大小的UIImage
-(UIImage )imgWithScreenSizedImage:(UIImage)image{
CGFloat origWidth = image.size.width;
CGFloat screenWidth = [UIScreen mainScreen].bounds.size.width;
CGFloat origHeight = image.size.height;
CGFloat screenHeight = [UIScreen mainScreen].bounds.size.height;

if ( origWidth <= screenWidth && origHeight <= screenHeight) { return image; }

NSLog(@"图片像素尺寸过大,压缩前w%f,h%f", origWidth, origHeight);
CGFloat max = MAX(origWidth, origHeight);
CGFloat scale = max/(screenHeight * 2.0f);//如果是6plus等设备，比例应该是3.0
NSLog(@"压缩后w%f,h%f", origWidth/scale, origHeight/scale);
return [self imgWithImage:image scaledToSize:CGSizeMake(origWidth/scale, origHeight/scale)];


}

-(UIImage )imgWithImage:(UIImage)image scaledToSize:(CGSize)newSize{
UIGraphicsBeginImageContext(newSize);
[image drawInRect:CGRectMake(0, 0, newSize.width, newSize.height)];
UIImage* newImage = UIGraphicsGetImageFromCurrentImageContext();
UIGraphicsEndImageContext();
return newImage;
}

**Comment by kingsic** [comment]
我在github上的SGQRCode仓库里附上您的邮箱号了（您去看一下）介意吗？介意的话，可以删除的

在 2017-03-27 18:49:48，"kingsic" <kingsic@126.com> 写道：

非常感谢，过段时间就会处理这个问题




发自网易邮箱大师
在2017年03月27日 18:18，neo6 写道：

我试了一下 既然只有截图大小的图片被识别，因此可以将我们自己选的图片先进行缩小处理（如果超过屏幕尺寸），这样普通图片就可以跟截图一样被正常识别了

添加如下处理，返回给选择后的回调方法-scanQRCodeFromPhotosInTheAlbum

//返回不超过屏幕尺寸大小的UIImage
-(UIImage )imgWithScreenSizedImage:(UIImage)image{
CGFloat origWidth = image.size.width;
CGFloat screenWidth = [UIScreen mainScreen].bounds.size.width;
CGFloat origHeight = image.size.height;
CGFloat screenHeight = [UIScreen mainScreen].bounds.size.height;

if ( origWidth <= screenWidth && origHeight <= screenHeight) { return image; }

NSLog(@"图片像素尺寸过大,压缩前w%f,h%f", origWidth, origHeight);
CGFloat max = MAX(origWidth, origHeight);
CGFloat scale = max/(screenHeight * 2.0f);//如果是6plus等设备，比例应该是3.0
NSLog(@"压缩后w%f,h%f", origWidth/scale, origHeight/scale);
return [self imgWithImage:image scaledToSize:CGSizeMake(origWidth/scale, origHeight/scale)];


}

-(UIImage )imgWithImage:(UIImage)image scaledToSize:(CGSize)newSize{
UIGraphicsBeginImageContext(newSize);
[image drawInRect:CGRectMake(0, 0, newSize.width, newSize.height)];
UIImage* newImage = UIGraphicsGetImageFromCurrentImageContext();
UIGraphicsEndImageContext();
return newImage;
}
