### ISSUE TITLE
bundle 文件读取不到数据

### ISSUE THREAD

**Issue by SYLing** [kingsic/SGQRCode#110]
【SGQRCodeScanningView 类 】
_scanningImageName = @"SGQRCode.bundle/QRCodeScanningLine";

【SGQRCodeScanManager类 playSoundName：方法】
NSString *audioFile = [[NSBundle mainBundle] pathForResource:name ofType:nil];
NSURL *fileUrl = [NSURL fileURLWithPath:audioFile];
    
读取bundle 为空。

**Comment by kingsic** [comment]
建议使用最新版本 @SYLing
