### ISSUE TITLE
特殊情况：后置摄像头不可用时crash

### ISSUE THREAD

**Issue by PlacidoLv** [kingsic/SGQRCode#123]
我这边有个设备后置摄像头坏了，然后打开扫描时会自动使用前摄像头，但是貌似前置摄像头不支持1920x1080导致crash。
原因：
Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[AVCaptureSession addInput:] Can't add <AVCaptureDeviceInput: 0x15d0b89e0 [前置相机]> because the device does not support AVCaptureSessionPreset1920x1080 - Use -[AVCaptureDevice supportsAVCaptureSessionPreset:]'
*** First throw call stack:
(0x182b56d8c 0x181d105ec 0x1886599c4 0x101bf8c88 0x100cf0834 0x100cf04dc 0x100cefbec 0x18c7f165c 0x18c7f13cc 0x18caaf438 0x18c81ea4c 0x18c81e6a4 0x18c8123a8 0x18c76a6f4 0x186cdfe54 0x186ce3fe4 0x186c506c8 0x186c781b0 0x18cb43518 0x18d1205d0 0x18d119368 0x182aff404 0x182afec2c 0x182afc79c 0x182a1cda8 0x184a02020 0x18ca3c758 0x100bf1170 0x1824adfc0)
libc++abi.dylib: terminating with uncaught exception of type NSException

请问不支持前置摄像头扫描吗？下个版本修复下吗？

**Comment by kingsic** [comment]
app 暂未没发现有支持前置摄像头扫描的<br>
一种解决方案是：判断后置摄像头是否受损<br>
另外一种就是：设置会话识别率支持前置摄像头 @PlacidoLv

**Comment by douxindong** [comment]
device does not support AVCaptureSessionPreset1920x1080
https://github.com/kingsic/SGQRCode/issues/140#issue-483733312
