### ISSUE TITLE
第一次拒绝给相机权限，下次再次点击就会崩溃

### ISSUE THREAD

**Issue by ohhkkk** [kingsic/SGQRCode#125]
SGQRCodeObtain 中的- (void)establishQRCodeObtainScanWithController:(UIViewController *)controller configure:(SGQRCodeObtainConfigure *)configure  中的  // 4(3)、添加捕获设备输入流到会话对象
    [_captureSession addInput:deviceInput];

**Comment by ghostlordstar** [comment]
我提了一个pull request，可以解决这个崩溃问题
