### ISSUE TITLE
建议：二维码扫描结果处理自定义和加入pod

### ISSUE THREAD

**Issue by hanweixing** [kingsic/SGQRCode#13]
首先谢谢作者提供了这样一个很好的封装。
我就拷贝文件夹直接拿过来用了，但是因为和demo是紧密联系在一起的，所以我还要自己用闭包来自己处理结果，虽然工作量不大，但是希望作者可以把这个封装的结果处理交给开发者，甚至把这个加入pod中进行管理

**Comment by kingsic** [comment]
听取您的建议已解决这个问题；2.0版本，用继承，更加方便 @hanweixing
