### ISSUE TITLE
二维码和条形码的metadataObjectTypes同时设置条码扫描不出来，二维码秒出

### ISSUE THREAD

**Issue by yangxiutao** [kingsic/SGQRCode#141]
metadataObjectTypes中同时设置二维码和条形码扫描格式，二维码秒出，条码扫描不出来；
metadataObjectTypes去除二维码的扫码格式，只设置条码的扫码格式，条码秒出；

请问：能不能同时设置二维码和条码格式，都能扫描出结果？

**Comment by moselon** [comment]
你好，你有找到扫描二维码和条形码好库码

**Comment by yangxiutao** [comment]
> 你好，你有找到扫描二维码和条形码好库码

他这个有个限制的扫描区域，你可以把这个扫描区域放开应该就可以了，在 SGQRCodeObtainConfigure类中有个rectOfInterest属性，你可以尝试着改改这个，我这边是直接注释掉了

**Comment by moselon** [comment]
NSArray *arr = @[AVMetadataObjectTypeQRCode, AVMetadataObjectTypeEAN13Code, AVMetadataObjectTypeEAN8Code, AVMetadataObjectTypeCode128Code,AVMetadataObjectTypeInterleaved2of5Code,AVMetadataObjectTypeCode39Code,AVMetadataObjectTypeEAN13Code];
    configure.metadataObjectTypes = arr;  我这写对吗，我看扫描条形码有点满，手机离条形码远一点距离就扫描不出来

**Comment by 1365102044** [comment]
我即使加上 _metadataObjectTypes = @[AVMetadataObjectTypeQRCode,AVMetadataObjectTypeEAN13Code, AVMetadataObjectTypeEAN8Code, AVMetadataObjectTypeCode128Code,AVMetadataObjectTypeInterleaved2of5Code,AVMetadataObjectTypeCode39Code,AVMetadataObjectTypeEAN13Code];依然扫不出条形码
