### ISSUE TITLE
希望提供改变“扫描线 颜色”的属性

### ISSUE THREAD

**Issue by CoderChenJun** [kingsic/SGQRCode#147]
作者提供了横线、网格线两种方式非常好，但是还希望作者后期能够提供改变图片颜色的属性。
如：

@property (nonatomic, strong) UIColor *scanImageColor;

_scanningline.image = [_scanningline.image imageWithRenderingMode:UIImageRenderingModeAlwaysTemplate];

_scanningline.tintColor = scanImageColor;

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo作者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA

**Comment by my-lsk** [comment]
你好，问题解决了吗
