### ISSUE TITLE
SGQRCode v3.0.1 没有摄像头权限时崩溃

### ISSUE THREAD

**Issue by zj381652512** [kingsic/SGQRCode#161]
处理方法:

- (void)establishQRCodeObtainScanWithController:(UIViewController *)controller {

    ......

    // 4(3)、添加捕获设备输入流到会话对象
    if ([_captureSession canAddInput:deviceInput]) { // add by zj
        [_captureSession addInput:deviceInput];
    }
    // add by zj
    BOOL isContains = YES;
    NSArray *availableTypes = metadataOutput.availableMetadataObjectTypes;
    for (NSString *type in configure.metadataObjectTypes) {
        if (![availableTypes containsObject:type]) {
            isContains = NO;
            break;
        }
    }
    // 5、设置数据输出类型，需要将数据输出添加到会话后，才能指定元数据类型，否则会报错
    if (isContains) {
        metadataOutput.metadataObjectTypes = configure.metadataObjectTypes;
    }

    ......

}

**Comment by songlicheng** [comment]
设备不支持的时候也可能奔溃，我这边是通过取交集进行赋值保证赋值是有效的
(void)establishQRCodeObtainScanWithController:(UIViewController *)controller {

......

// 4(3)、添加捕获设备输入流到会话对象
if ([_captureSession canAddInput:deviceInput]) { 
[_captureSession addInput:deviceInput];
}
NSArray *availableTypes = metadataOutput.availableMetadataObjectTypes;
NSMutableSet *availableTypesSet = [NSMutableSet setWithArray:availableTypes];
NSMutableSet *configTypesSet = [NSMutableSet setWithArray:configure.metadataObjectTypes];
[configTypesSet intersectSet:availableTypesSet];
NSArray *metadataTypes = [configTypesSet allObjects];
metadataOutput.metadataObjectTypes = metadataTypes;

......

}
