### ISSUE TITLE
iphone 6 crash

### ISSUE THREAD

**Issue by JackyL90** [kingsic/SGQRCode#163]
reason: *** -[AVCaptureSession addInput:] Can't add <AVCaptureDeviceInput: 0x281c50a00 [后置镜头]> because the device does not support AVCaptureSessionPreset3840x2160 - Use -[AVCaptureDevice supportsAVCaptureSessionPreset:]

**Comment by vlay1314** [comment]
iphone6已运行就奔溃，这个问题一直没有修复吗？

**Comment by 854907646** [comment]
我也碰到了，iPhone6一直运行奔溃

**Comment by JIAiOS** [comment]
这个问题可能是不支持这么高的分辨率，在SGQRCodeManager.m找到_canSetSessionPreset这个方法，注释掉【if ([self.session canSetSessionPreset:AVCaptureSessionPreset3840x2160])】这个方法，其他的保留。就解决了。
