### ISSUE TITLE
这个carsh有可能是什么原因啊

### ISSUE THREAD

**Issue by dsisi** [kingsic/SGQRCode#172]
![image](https://user-images.githubusercontent.com/18209627/145759954-0f18103f-b5fb-4a01-bbd6-9f7cd4d0db16.png)
![image](https://user-images.githubusercontent.com/18209627/145759991-ec0e1f53-7c3d-43f9-98de-1df0253bdf95.png)

**Comment by kingsic** [comment]
这个不是本库的原因

建议：
全局断点调试，分析崩溃原因
也可添加QQ群或我的联系方式，近一步分析解决问题 @dsisi
