### ISSUE TITLE
二维码存在问题

### ISSUE THREAD

**Issue by liusongCode** [kingsic/SGQRCode#2]
0.进入相册选择图片直接卡死
1.二维码生成数据  能否由用户自己决定 生成二维码数据采集这边希望能够补上 [集成类似二维码生成器功能 这个暂时没有发现有什么用]
2.因为二维码扫描之后的有可能要上传到电脑   类似超市二维码扫描就上传到超市电脑的功能  
[二维码扫描完成之后上传到电脑的功能    因为一般电脑没有搭建相应的服务器 可以考虑TCP Socket的方式进行数据传递  
传输信息类型 因为二维码数据一般不是很大   一般就是一些文字什么的 可以提供上传字符串  上传图片与字符串混合模式]
3.上个版本不需要用户修改Bundle ID 不知道为什么这一版非要修改才能进行真机功能

**Comment by kingsic** [comment]
1、从相册中选择照片读取二维码需要iOS8以后的系统才能够支持，在我这测试一直没有出现卡死现象(你在测试，若是再出现卡死现象， 请把截图以及相关信息发给我)；
2、这个二维码生成你只需要从上个界面传值过来即刻生成你需要的二维码(// 2、设置数据
    NSString *string_data = @"https://github.com/kingsic";)，在设置数据这里设置就可以了；至于你说的需要传给服务器，你可以根据你项目的需求，用AFN去解决这块问题 @liusongCode
