### ISSUE TITLE
pop回扫描界面界面卡主

### ISSUE THREAD

**Issue by pyooboom** [kingsic/SGQRCode#24]
在展示扫描结果的界面，你这边对返回的处理是直接pop到根控制器，如果返回扫描界面，扫描界面会卡住，这是为什么呢？

**Comment by kingsic** [comment]
扫描界面之间的逻辑处理是模仿微信扫一扫的；根据你的需求，你可以在 SGQRCodeScanningVC.m 对扫描界面的创建以及移除做相应的处理 @pyooboom
