### ISSUE TITLE
SGQRCodeScanningVC模块封装

### ISSUE THREAD

**Issue by wyfSunflower** [kingsic/SGQRCode#26]
你好！你的SGQRCodeScanningVC是一个控制器，我现在想封装成一个轻量级的独立模块，同时又留足够多的接口供外界调用。扫描需要用到input output session previewLayer及其delegate，我想把这个封装成CALayer的子类，但是在设置时遇到很多问题

**Comment by bluesky0109** [comment]
@wyfSunflower 可以看看 [YFCodeScan](https://github.com/bluesky0109/YFCodeScan)，scanner、preview、controller都是分离的，可自由组合定制
