### ISSUE TITLE
文本二维码文字太多问题

### ISSUE THREAD

**Issue by YangLiMey** [kingsic/SGQRCode#28]
让很多文字生成一个二维码，二维码密度增加，这种情况下怎么处理呢？我试的时候发现一直在扫描页面，没有什么反应，大概在700字以上文字生成的二维码扫描时就这样了，想问问大神有没有这一块的处理。

**Comment by like359881584** [comment]
公司内部做测试时我也遇到过类似的问题，二维码密度达到一定时，手机的相机像素 已经无法分辨了，我的办法是：将文字进行了截取，展示成 多个二维码，手动点击 进行一张一张的替换， 一张一张的扫描， 最后将扫描到的进行拼接。。。
