### ISSUE TITLE
从相册中选取照片识别二维码不成功

### ISSUE THREAD

**Issue by ShayneChow** [kingsic/SGQRCode#3]
iOS10 6plus / Xcode 8 测试识别二维码不成功（不会crash）

`NSArray *features = [detector featuresInImage:[CIImage imageWithCGImage:image.CGImage]];`
初步判断是这个部分的问题，feature为nil，暂时没找到解决方法。

**Comment by kingsic** [comment]
检测一下你扫描的二维码里面有没有数据，换一张二维码进行扫描，看看会不会出现这种问题；刚才我自己这测试了一下，并没有出现问题；。另外，感谢你提醒我用 iOS 10 测试，及时解决了相机访问权限崩溃的问题 @ShayneChow

**Comment by ShayneChow** [comment]
我是拿扫描先测试的二维码有返回结果的，再拍照保存到相册，供读取识别。

**Comment by kingsic** [comment]
在你手机上用截图的方法截取二维码， 再测试，看看是否为 nil ；如果还是出现了，请把你的 Demo 以及 照片发过来， 我来测试一下看 @ShayneChow

**Comment by LxwYl** [comment]
相册里面的二维码扫描问题怎么解决的？

**Comment by stackJolin** [comment]
你好，我也遇到这个问题了，ios10，6plus截图的二维码扫描不出来，其他的手机可以扫描出来
