### ISSUE TITLE
能不能把工具库上传到pod？这样使用起来更方便

### ISSUE THREAD

**Issue by lichanghong** [kingsic/SGQRCode#32]
能不能把工具库上传到pod？这样使用起来更方便

**Comment by kingsic** [comment]
已加入 pods 管理 @lichanghong

**Comment by DarielChen** [comment]
$ pod search SGQRCode
[!] Unable to find a pod with name, author, summary, or description matching `SGQRCode`

**Comment by kingsic** [comment]
有时候即使 pod search 找不到仓库，也是可以安装的；
http://www.jianshu.com/p/d2d81b58d716  这个链接告诉你怎么解决 pod search 仓库找不到的问题 @DarielChen

**Comment by DarielChen** [comment]
$ pod install
Analyzing dependencies
[!] Unable to find a specification for `SGQRCode`
