### ISSUE TITLE
界面跳转卡顿，体验太差

### ISSUE THREAD

**Issue by wyk190576528** [kingsic/SGQRCode#37]
首页点击扫描二维码，会卡顿一会后再push到扫描界面

**Comment by JamhonyZ** [comment]
在SGQRCodeScanManager.m 方法 setupSessionPreset …… 里 ，[_session startRunning]  代码延迟0.001秒执行。
微信效果：在viewDidLoad里赋值 self.view 背景色为黑色。然后在 上面 延迟代码里，执行currentController.view.backgroundColor = [UIColor clearColor];

**Comment by wyk190576528** [comment]
一直在疑惑微信怎么实现的，谢谢大神

**Comment by Bobo-Wang** [comment]
第一次点击push不卡顿，之后点击会感觉有点反应迟钝的感觉

**Comment by bluesky0109** [comment]
@wyk190576528 可以试试 [YFCodeScan](https://github.com/bluesky0109/YFCodeScan)，秒开 不卡主线程
