### ISSUE TITLE
进入扫码页面后如果返回上一级页面 brightnessValue屏幕亮度会持续获取并输出打印

### ISSUE THREAD

**Issue by guodongZhao** [kingsic/SGQRCode#44]
进入扫一扫页面后不扫码直接返回上一级页面，- (void)captureOutput:(AVCaptureOutput *)captureOutput didOutputSampleBuffer:(CMSampleBufferRef)sampleBuffer fromConnection:(AVCaptureConnection *)connection方法会持续运行，brightnessValue持续输出打印，只有在完全退出后台后才会停止，求解决方案。

**Comment by lzsJohnson** [comment]
把 setupQRCodeScanning 方法的 SGQRCodeScanManager * manager  换成全局的，在viewWillDisappear里面调用[_manager SG_stopRunning]; 就好了

**Comment by kingsic** [comment]
这是时刻监听根据光线强弱的代理方法，内存是保持平稳的（留意的话你会看到的），不用担心这个；如果不需要根据光线强弱打开手电筒，可以注释掉相关代码 @guodongZhao

**Comment by guodongZhao** [comment]
好的  感谢
