### ISSUE TITLE
扫描跳转后，再回到扫描界面视角卡主不动

### ISSUE THREAD

**Issue by a289459798** [kingsic/SGQRCode#45]
扫描跳转后，再回到扫描界面视角卡主不动

**Comment by kingsic** [comment]
扫描界面逻辑处理是仿微信逻辑，具体其他业务逻辑，可参考方法，自行处理 @a289459798

**Comment by a289459798** [comment]
扫描完成之后，SG_stopRunning 然后再SG_startRunning，页面还是卡住

**Comment by a289459798** [comment]
我看源码是因为在SG_stopRunning 里面把_session = nil，如果需要重新开启的话，如何弄比较合理

**Comment by kingsic** [comment]
一、在扫描方法中注释掉 [scanManager SG_videoPreviewLayerRemoveFromSuperlayer];  这句代码
二、再注释掉 _session = nil 这句代码；即可扫描之后停留扫描界面继续扫描了 @a289459798

**Comment by a289459798** [comment]
_session = nil 这个去掉的话，会不会造成内存泄露之内的问题呢？
@kingsic

**Comment by liuxinixn** [comment]
还是不行呀，内容并没有清掉。扫描过后的内容还是存在

**Comment by huangzhifei** [comment]
主要是 videoPreviewLayerRemoveFromSuperlayer 的问题，只需要在特定地方和场景调用一下就能解决这个问题。
