### ISSUE TITLE
如果用户关闭相机权限，再扫描直接崩溃

### ISSUE THREAD

**Issue by lihuichina** [kingsic/SGQRCode#5]
如果用户关闭相机权限，再扫描直接崩溃，同样是不是要先如果用户关闭相机权限的话 提示他打开，

**Comment by kingsic** [comment]
已解决，谢谢 @lihuichina

**Comment by lihuichina** [comment]
用户关闭相机权限时  在扫码 就闪退 没有解决啊 ，我在扫码界面viewwill里写判断是否获取相机权限时，如果没有就return 提示时 也闪退 是怎么回事

**Comment by kingsic** [comment]
真机运行之后，拔掉数据线进行测试


发自网易邮箱大师
在2016年12月28日 17:21，lihuichina 写道:

用户关闭相机权限时 在扫码 就闪退 没有解决啊 ，我在扫码界面viewwill里写判断是否获取相机权限时，如果没有就return 提示时 也闪退 是怎么回事

**Comment by lwcass** [comment]
SGScanningQRCodeVC.m  122行  出了问题 你在viewwill加判断没用

**Comment by kingsic** [comment]
相机崩溃问题，请用真机测试


发自网易邮箱大师
在2017年02月13日 11:42，lwcass 写道：

SGScanningQRCodeVC.m 122行 出了问题 你在viewwill加判断没用

**Comment by lwcass** [comment]
是真机测试啊  授权了相机然后再关闭相机授权 就有这问题  你可以试试

**Comment by kingsic** [comment]
数据线，拔掉


发自网易邮箱大师
在2017年02月13日 12:23，lwcass 写道：

是真机测试啊 授权了相机然后再关闭相机授权 就有这问题 你可以试试

**Comment by lwcass** [comment]
拔了哇

**Comment by lwcass** [comment]
明显是忽略了 相机权限导致的  优化下吧  扫描二维码点击事件中 你只判断了相册权限 而忽略了相机权限

**Comment by lihuichina** [comment]
我是在我的项目需求改了下 在 viewDidLoad  里判断用户权限弄好了 不过题主真的没有判断用户是否有相机权限呀，没给权限时运行时崩了

**Comment by lwcass** [comment]
是的  自己加一下 就可以了

**Comment by kingsic** [comment]
问题已解决，谢谢


发自网易邮箱大师
在2017年02月13日 15:16，lwcass 写道：

是的 自己加一下 就可以了

**Comment by kingsic** [comment]
你可以下载，最新的代码，解决了相机崩溃问题以及第一次访问相机，相册及其缓慢问题。同时，也非常感谢您提出的宝贵建议，让我意识到代码的错误性


发自网易邮箱大师
在2017年02月13日 15:16，lwcass 写道：

是的 自己加一下 就可以了
