### ISSUE TITLE
内存泄漏

### ISSUE THREAD

**Issue by Beyond-Chao** [kingsic/SGQRCode#53]
1. CGColorSpaceRef colorSpace = CGColorSpaceCreateDeviceGray();
2. CGImageRef scaledImage = CGBitmapContextCreateImage(bitmapRef);

这两句存在内存泄漏，

需要调用相关release方法释放内存
1.     CGColorSpaceRelease(colorSpace);
2.     CGImageRelease(scaledImage);

**Comment by swagallagher** [comment]
我也遇到了。。。
