### ISSUE TITLE
进相册扫描二维码崩溃

### ISSUE THREAD

**Issue by zp18862956943** [kingsic/SGQRCode#56]
崩在 NSArray *features = [detector featuresInImage:[CIImage imageWithCGImage:image.CGImage]];这一行，有遇到相同问题的吗

**Comment by figureai** [comment]
请问你是怎么解决的

**Comment by smileat** [comment]
我也是这样的问题，你解决了吗？这个为什么关闭呀

> 请问你是怎么解决的
