### ISSUE TITLE
如果想将条码和图片都传到下一个控制器应该怎么弄

### ISSUE THREAD

**Issue by 61661726** [kingsic/SGQRCode#6]
二维码/条码 扫描成功之后, 我想截取扫描范围内的图片 然后和条码一起传到下个控制器 ,   应该怎么截取扫描范围内的图片?

**Comment by kingsic** [comment]
不太清楚你描述的问题，要是扫描H5上面的数据，展示H5上面的图片，可结合webView解决 @61661726
