### ISSUE TITLE
苹果审核不通过

### ISSUE THREAD

**Issue by CoderLike** [kingsic/SGQRCode#65]
原因:需要在具体界面提示"xxx想访问您的相机/相册".demo中点击扫描二维码或者点击相册时就弹出上述描述框,这是苹果不允许的.
解决:需要进入到扫描界面或者相册界面再进行调用<AV...>相关框架,引出提示框!

**Comment by wangkai1988** [comment]
这个错误可能是你的info.plist中的使用描述不明晰造成的，需要写清楚为什么访问相机/相册，比如“App需要访问相机/相册，来获取您的相片”
