### ISSUE TITLE
如何设置扫描区域

### ISSUE THREAD

**Issue by hugolubingshen** [kingsic/SGQRCode#66]
能控制扫描区域吗？现在有没有那个扫描框都无所谓的，能直接扫描，能控制只能扫描框才能扫描吗

**Comment by DabbyCHEN** [comment]
同问，应该在框内才能扫吧，框外的能扫就没意义了

**Comment by wyk190576528** [comment]
同问，改用AVCaptureMetadataOutput扫描吧，这样可以设置rectOfInterest来控制扫描区域了，坐等更新

**Comment by wyk190576528** [comment]
项目中可设置扫描区域
metadataOutput.rectOfInterest = CGRectMake(0.05, 0.2, 0.7, 0.6);
