### ISSUE TITLE
WB,WC使用上有什么区别?

### ISSUE THREAD

**Issue by shang1219178163** [kingsic/SGQRCode#91]
![2018-05-19 15 02 13](https://user-images.githubusercontent.com/3699729/40265996-a6c8b0f2-5b75-11e8-86cf-a584501413e0.png)

**Comment by qk514112** [comment]
@shang1219178163 WBQRCode(popVC 逻辑处理) 扫码成功后进入web页，back时返回到扫码页面；
WCQRCode(popToRootVC 逻辑处理) 扫码成功后进入web页，back时返回到主页；WCQRcode在暗处还会弹出打开手电筒的图标。
